Repository vasu-1/CalcHub, pull requests merged in 2022-06, with the labels that each got.

#340 Fraction (done changes 👍)
  Calculators/Fraction Calculator/index.html
  Calculators/Fraction Calculator/readme.md
  Calculators/Fraction Calculator/script.js
  Calculators/Fraction Calculator/style.css
Labels: GSSoC22, ready for merge

#309 Enhancement in Temperature Calculator
  Calculators/Temperature_Calculator/index.html
  Calculators/Temperature_Calculator/readme.md
  Calculators/Temperature_Calculator/script.js
Labels: GSSoC22, changes

#357 arranged calculator list in ascending order
  README.md
Labels: review_needed, CX
