Repository vasu-1/CalcHub, pull requests merged in 2022-03, with the labels that each got.

#18 Add Statistics Calculator
  Calculators/Statistics Calculator/README.md
  Calculators/Statistics Calculator/index.html
  Calculators/Statistics Calculator/script.js
  Calculators/Statistics Calculator/styles.css
  README.md
Labels: GSSoC22, Good Issue

#46 Temperature Calculator
  Calculators/Temperature_Calculator/index.html
  Calculators/Temperature_Calculator/readme.md
  Calculators/Temperature_Calculator/script.js
  Calculators/Temperature_Calculator/style.css
  README.md
Labels: GSSoC22, ready for merge

#55 Added BaseX_Calculator files
  Calculators/BaseX_Calculator/app.js
  Calculators/BaseX_Calculator/index.html
  Calculators/BaseX_Calculator/readme.md
  Calculators/BaseX_Calculator/style.css
  README.md
Labels: review_needed, GSSoC22, changes

#56 added quadratic equation calculator
  Calculators/Quadratic_Equation_Calculator/README.md
  Calculators/Quadratic_Equation_Calculator/app.js
  Calculators/Quadratic_Equation_Calculator/index.html
  Calculators/Quadratic_Equation_Calculator/styles.css
Labels: GSSoC22, ready for merge, PR reviewed

#36 added simple interest Calculator folder
  Calculators/Simple_Interest/index.html
  Calculators/Simple_Interest/readme.md
  Calculators/Simple_Interest/script.js
  Calculators/Simple_Interest/style.css
Labels: GSSoC22

#94 Added Binary calculator
  Calculators/Binary_Calculator/index.css
  Calculators/Binary_Calculator/index.html
  Calculators/Binary_Calculator/index.js
  Calculators/Binary_Calculator/readme.md
  README.md
Labels: GSSoC22, ready for merge

#93 added Prime Factor Calculator
  Calculators/PrimeFactors_Calculator/README.md
  Calculators/PrimeFactors_Calculator/index.html
  Calculators/PrimeFactors_Calculator/script.js
  Calculators/PrimeFactors_Calculator/style.css
  README.md
Labels: GSSoC22, ready for merge

#69 New Calculator Added:Number System Conversion Calculator
  Calculators/NumberSystemCoversion_Calculator/README.md
  Calculators/NumberSystemCoversion_Calculator/index.html
  Calculators/NumberSystemCoversion_Calculator/operation.js
  Calculators/NumberSystemCoversion_Calculator/style.css
  Calculators/Simple_Arithmetic/index.html
Labels: GSSoC22, ready for merge, PR reviewed

#47 Add Matrix Adjoint And Inverse Calculator
  Calculators/Matrix Adjoint and Inverse Calculator/README.md
  Calculators/Matrix Adjoint and Inverse Calculator/index.html
  Calculators/Matrix Adjoint and Inverse Calculator/scripts/main.js
  Calculators/Matrix Adjoint and Inverse Calculator/styles/styles.css
Labels: GSSoC22, Level2

#52 Visual Type Scale Calculator
  Calculators/Visual Type Scale Calculator/README.md
  Calculators/Visual Type Scale Calculator/index.html
  Calculators/Visual Type Scale Calculator/script.js
  Calculators/Visual Type Scale Calculator/style.css
Labels: GSSoC22, ready for merge, PR reviewed

#83 BaseX to BaseY Calculator
  Calculators/BaseX_Calculator/app.js
  Calculators/BaseX_Calculator/index.html
  Calculators/BaseX_Calculator/readme.md
  Calculators/BaseX_Calculator/style.css
Labels: Good Issue

#105 Adding Affine Cipher Calculator, resolving issue #64, update on #101
  Calculators/Affine_Cipher_Calculator/index.html
  Calculators/Affine_Cipher_Calculator/readme.md
  Calculators/Affine_Cipher_Calculator/style.css
Labels: review_needed, GSSoC22

#109 Added Roman to integer
  Calculators/Roman_To_Integer_Calculator/index.html
  Calculators/Roman_To_Integer_Calculator/readme.md
  Calculators/Roman_To_Integer_Calculator/script.js
  Calculators/Roman_To_Integer_Calculator/styles.css
Labels: GSSoC22, ready for merge, PR reviewed

#114 Transpose of 3x3 Matrix Calculator
  Calculators/Transpose_3X3_Matrix_Calculator/README.md
  Calculators/Transpose_3X3_Matrix_Calculator/index.html
  Calculators/Transpose_3X3_Matrix_Calculator/script.js
  Calculators/Transpose_3X3_Matrix_Calculator/style.css
Labels: GSSoC22, ready for merge, PR reviewed

#107 Euclidean Algorithm Calculator_#59
  Calculators/Euclidean_Algorithm_Calculator/README.md
  Calculators/Euclidean_Algorithm_Calculator/app.js
  Calculators/Euclidean_Algorithm_Calculator/index.html
  Calculators/Euclidean_Algorithm_Calculator/style.css
Labels: GSSoC22, Level1

#121 Log and antilog Calculator added
  Calculators/Log_Calculator/Log.css
  Calculators/Log_Calculator/Log.html
  Calculators/Log_Calculator/Log.js
  Calculators/Log_Calculator/readme.md
  README.md
Labels: GSSoC22, Level1

#112 Tax Calculation, Fixed as per Indian tax Slab
  Calculators/IncomeTaxCalculator/index.html
Labels: review_needed, GSSoC22

#144 Stock Profit Calculator
  Calculators/Stock_Profit _And_Loss_Calculator/README.md
  Calculators/Stock_Profit _And_Loss_Calculator/app.js
  Calculators/Stock_Profit _And_Loss_Calculator/index.html
  Calculators/Stock_Profit _And_Loss_Calculator/styles.css
  README.md
Labels: GSSoC22, ready for merge, PR reviewed

#141 Digital Storage Calculator Added
  Calculators/Digital_Storage_Calculator/README.md
  Calculators/Digital_Storage_Calculator/convert.js
  Calculators/Digital_Storage_Calculator/index.html
  Calculators/Digital_Storage_Calculator/style.css
Labels: GSSoC22, ready for merge

#137 Added Catalan number calculator
  Calculators/Catalan_Number_Calculator/app.js
  Calculators/Catalan_Number_Calculator/index.html
  Calculators/Catalan_Number_Calculator/readme.md
  Calculators/Catalan_Number_Calculator/styles.css
Labels: GSSoC22, ready for merge

#131 Currency Calculator Added
  Calculators/Currency_Calculator/README.md
  Calculators/Currency_Calculator/convert.js
  Calculators/Currency_Calculator/index.html
  Calculators/Currency_Calculator/style.css
Labels: GSSoC22, ready for merge

#130 Adding modulo and inverse modulo caclulator, Resolving issue #99
  Calculators/Modulo_Inverse-Modulo_Calculator/index.html
  Calculators/Modulo_Inverse-Modulo_Calculator/readme.md
  Calculators/Modulo_Inverse-Modulo_Calculator/style.css
Labels: GSSoC22, ready for merge

#102 Added Color Code Calculator files
  Calculators/Color_Code_Converter/assets/css/style.css
  Calculators/Color_Code_Converter/index.html
  Calculators/Color_Code_Converter/readme.md
  Calculators/Color_Code_Converter/scripts/app.js
Labels: GSSoC22, changes

#157 EMI Calculator
  Calculators/EMI_Calculator/README.md
  Calculators/EMI_Calculator/index.css
  Calculators/EMI_Calculator/index.html
  Calculators/EMI_Calculator/index.js
Labels: GSSoC22, ready for merge, PR reviewed

#98 New PR for BMI Calculator
  Calculators/BMI_Calculator/index.html
  Calculators/BMI_Calculator/index.js
  Calculators/BMI_Calculator/readme.md
  Calculators/BMI_Calculator/styles.css
Labels: GSSoC22, Level1

#119 Gpa calculator
  Calculators/GPA_Calculator/index.html
  Calculators/GPA_Calculator/js/index.js
  Calculators/GPA_Calculator/readme.md
  Calculators/GPA_Calculator/styles/style.css
Labels: GSSoC22, changes

#132 Added Permutation and Combination calculator
  Calculators/Permutation and Combination Calculator/README.md
  Calculators/Permutation and Combination Calculator/index.html
  Calculators/Permutation and Combination Calculator/script.js
  Calculators/Permutation and Combination Calculator/style.css
Labels: GSSoC22, changes

#149 DayCalculator
  Calculators/DayCalculator/DayCalculator.css
  Calculators/DayCalculator/DayCalculator.js
  Calculators/DayCalculator/README.md
  Calculators/DayCalculator/index.html
Labels: GSSoC22, ready for merge

#168 Sleep Calculator added
  Calculators/Sleep_Calculator/index.html
  Calculators/Sleep_Calculator/readme.md
  Calculators/Sleep_Calculator/script.js
  Calculators/Sleep_Calculator/style.css
Labels: GSSoC22, Level1

#170 Added Cubic_Equation_Calc files
  Calculators/Cubic_Equation_Calc/assets/css/bootstrap.css
  Calculators/Cubic_Equation_Calc/assets/css/bootstrap.css.map
  Calculators/Cubic_Equation_Calc/assets/css/style.css
  Calculators/Cubic_Equation_Calc/index.html
  Calculators/Cubic_Equation_Calc/readme.md
  Calculators/Cubic_Equation_Calc/scripts/app.js
  Calculators/Cubic_Equation_Calc/scripts/bootstrap.bundle.js
  Calculators/Cubic_Equation_Calc/scripts/bootstrap.bundle.js.map
  README.md
Labels: GSSoC22, Level2

#181 Complex Number Calculator added
  Calculators/Complex_Number_Calculator/README.md
  Calculators/Complex_Number_Calculator/app.js
  Calculators/Complex_Number_Calculator/index.html
  Calculators/Complex_Number_Calculator/style.css
Labels: GSSoC22, Level2

#185 Re-design and refactor Affine Cipher Calculator
  Calculators/Affine_Cipher_Calculator/calculator.js
  Calculators/Affine_Cipher_Calculator/index.html
  Calculators/Affine_Cipher_Calculator/interactionHandler.js
  Calculators/Affine_Cipher_Calculator/style.css
  Calculators/Simple_Arithmetic/index.html
Labels: enhancement, Good Issue
