Repository vasu-1/CalcHub, pull requests merged in 2022-10, with the labels that each got.

#362 added responsiveness for Matrix Adjoint and Inverse Calculator
  Calculators/Matrix Adjoint and Inverse Calculator/styles/styles.css
Labels: changes, hacktoberfest, hacktoberfest-accepted

#364 Wind chill calculator edited
  Calculators/Wind_Chill_Calculator/Styles/styles.css
  Calculators/Wind_Chill_Calculator/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#368 Issue & pull request template updated
  .github/ISSUE_TEMPLATE/bug-issue-form.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest

#369 ui-updated
  Calculators/Temperature_Calculator/index.html
  Calculators/Temperature_Calculator/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#370 done responsiveness and fixes
  Calculators/VAT_Calculator/Assets/css/style.css
  Calculators/VAT_Calculator/index.html
  Calculators/VAT_Calculator/script/script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#374 modified layout and validation and added responsive
  Calculators/NumberSystemCoversion_Calculator/README.md
  Calculators/NumberSystemCoversion_Calculator/index.html
  Calculators/NumberSystemCoversion_Calculator/operation.js
  Calculators/NumberSystemCoversion_Calculator/script.js
  Calculators/NumberSystemCoversion_Calculator/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#375 validation and reset functionality added in simple interest calculator
  Calculators/Simple_Interest/index.html
  Calculators/Simple_Interest/script.js
  Calculators/Simple_Interest/style.css
Labels: Good Issue, hacktoberfest, hacktoberfest-accepted

#376 Arithmatic Equation Solver Calculator Style Updated
  Calculators/Arithmatic Equation Solver/index.html
  Calculators/Arithmatic Equation Solver/style.css
Labels: enhancement, Good Issue, hacktoberfest, hacktoberfest-accepted
