Repository vasu-1/CalcHub, pull requests merged in 2022-05, with the labels that each got.

#256 Added Daily Water Intake Calculator
  Calculators/Daily_Water_Intake_Calculator/README.md
  Calculators/Daily_Water_Intake_Calculator/index.css
  Calculators/Daily_Water_Intake_Calculator/index.html
  Calculators/Daily_Water_Intake_Calculator/index.js
  README.md
Labels: GSSoC22, ready for merge

#259 Modified Currency Calculator with README file
  Calculators/Currency-Calculator/README.md
  Calculators/Currency-Calculator/index.html
  Calculators/Currency-Calculator/script.js
  Calculators/Currency-Calculator/style.css
  Calculators/Currency_Calculator/convert.js
  Calculators/Currency_Calculator/index.html
  Calculators/Currency_Calculator/style.css
Labels: GSSoC22, Level2

#210 Compound interest calculator
  Calculators/Compound interest Calculator/index.html
  Calculators/Compound interest Calculator/readme.md
  Calculators/Compound interest Calculator/runApp.js
  Calculators/Compound interest Calculator/style.css
Labels: GSSoC22, Level1

#287 Kinetic Theory of Gases Calculator #286
  Calculators/Kinetic_Theory_of_Gases_Calculator/README.md
  Calculators/Kinetic_Theory_of_Gases_Calculator/index.html
  Calculators/Kinetic_Theory_of_Gases_Calculator/particles.js
  Calculators/Kinetic_Theory_of_Gases_Calculator/script.js
  Calculators/Kinetic_Theory_of_Gases_Calculator/style.css
Labels: GSSoC22, ready for merge

#289 Electric vs Petrol Economy Price Calculator
  Calculators/Electric vs Petrol Economy Price Calculator/index.html
  Calculators/Electric vs Petrol Economy Price Calculator/readme.md
  Calculators/Electric vs Petrol Economy Price Calculator/script.js
  Calculators/Electric vs Petrol Economy Price Calculator/style.css
Labels: GSSoC22, ready for merge

#294 Divisors Calculator
  Calculators/Divisors Calculator/DivisorsCalc.css
  Calculators/Divisors Calculator/DivisorsCalc.js
  Calculators/Divisors Calculator/README.md
  Calculators/Divisors Calculator/index.html
Labels: GSSoC22, changes

#320 Bug Report Issue Template
  .github/ISSUE_TEMPLATE/bug-issue-form.yaml
Labels: CX

#323 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: CX

#306 ✔️Graph Calculator (check Deployment✔️) (changes done )
  Calculators/Graph Calculator/index.html
  Calculators/Graph Calculator/readme.md
  Calculators/Graph Calculator/script.js
  Calculators/Graph Calculator/style.css
Labels: GSSoC22, ready for merge

#329 Code Of Conduct Added
  README.md
Labels: CX

#240 Basic Physics Calculator
  Calculators/Basic_physics calculator/index.html
  Calculators/Basic_physics calculator/readme.md
  Calculators/Basic_physics calculator/script.js
  Calculators/Basic_physics calculator/styles.css
Labels: GSSoC22, Level2

#288 👍 Covid Calculator
  Calculators/Covid Calculator/index.html
  Calculators/Covid Calculator/readme.md
  Calculators/Covid Calculator/script.js
  Calculators/Covid Calculator/style.css
Labels: GSSoC22, changes

#341 Arithmetic Equation
  Calculators/Arithmatic Equation Solver/index.html
  Calculators/Arithmatic Equation Solver/script.js
  Calculators/Arithmatic Equation Solver/style.css
Labels: GSSoC22, Level2

#297 binomial coefficient calculator
  Calculators/Binomial_Coeff_Calc/App.css
  Calculators/Binomial_Coeff_Calc/App.html
  Calculators/Binomial_Coeff_Calc/App.js
  Calculators/Binomial_Coeff_Calc/readme.md
Labels: GSSoC22, Level1

#324 Simple arithmetic
  Calculators/Simple_Arithmetic/index.html
  Calculators/Simple_Arithmetic/js/script.js
  Calculators/Simple_Arithmetic/readme.md
  Calculators/Simple_Arithmetic/style.css
Labels: GSSoC22, changes

#332 Unit Converter added
  Calculators/Unit Converter/Readme.md
  Calculators/Unit Converter/index.html
  Calculators/Unit Converter/script.js
  Calculators/Unit Converter/style.css
Labels: GSSoC22, Good Issue, Level3

#345 Age Calculator Modified
  Calculators/Age_Calculator/app.js
  Calculators/Age_Calculator/readme.md
  Calculators/Age_Calculator/style.css
Labels: enhancement, GSSoC22, Level1

#347 Volume calculator
  Calculators/Volume Calculator/index.html
  Calculators/Volume Calculator/jsfile.js
  Calculators/Volume Calculator/readme.md
  Calculators/Volume Calculator/style.css
  README.md
Labels: GSSoC22, ready for merge

#346 Caeser Cipher Calculator Added
  Calculators/CaeserCipher_Calculator/Readme.md
  Calculators/CaeserCipher_Calculator/caeser.js
  Calculators/CaeserCipher_Calculator/caesercipher.html
  Calculators/CaeserCipher_Calculator/caesercss.css
Labels: GSSoC22, ready for merge
